<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <SccProjectName />
    <SccLocalPath />
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseOfMfc>false</UseOfMfc>
    <CharacterSet>MultiByte</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseOfMfc>false</UseOfMfc>
    <CharacterSet>MultiByte</CharacterSet>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="$(VCTargetsPath)Microsoft.Cpp.UpgradeFromVC60.props" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="$(VCTargetsPath)Microsoft.Cpp.UpgradeFromVC60.props" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <OutDir>.\Debug\</OutDir>
    <IntDir>.\Debug\</IntDir>
    <LinkIncremental>false</LinkIncremental>
    <IncludePath>C:\dev\All_SAR\3rdParty\Intel\IPP\5.2\ia32\include;C:\dev\All_SAR\Common\Include;$(IncludePath)</IncludePath>
    <LibraryPath>C:\dev\All_SAR\3rdParty\Microsoft\msxml4_SP3;c:\dev\All_SAR\3rdParty\Intel\IPP\5.2\ia32\stublib;$(LibraryPath)</LibraryPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <OutDir>.\Release\</OutDir>
    <IntDir>.\Release\</IntDir>
    <LinkIncremental>false</LinkIncremental>
    <TargetName>EMS$(ProjectName)</TargetName>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <ClCompile>
      <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
      <InlineFunctionExpansion>Default</InlineFunctionExpansion>
      <FunctionLevelLinking>false</FunctionLevelLinking>
      <Optimization>Disabled</Optimization>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <WarningLevel>Level3</WarningLevel>
      <MinimalRebuild>true</MinimalRebuild>
      <DebugInformationFormat>EditAndContinue</DebugInformationFormat>
      <AdditionalIncludeDirectories>..\common\include;..\3rdparty\microsoft\microsoft sdk\include;..\3rdparty\microsoft\MSXML4;..\..\common\include;..\..\3rdparty\microsoft\microsoft sdk\include;..\3rdparty\intel\ipp\5.2\ia32\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>_DEBUG;WIN32;_CONSOLE;_WIN32_WINNT=0x400;EMS_USE_INTEL_PP;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AssemblerListingLocation>.\Debug\</AssemblerListingLocation>
      <BrowseInformation>true</BrowseInformation>
      <PrecompiledHeaderOutputFile>.\Debug\DBFPassScheduler.pch</PrecompiledHeaderOutputFile>
      <ObjectFileName>.\Debug\</ObjectFileName>
      <ProgramDataBaseFileName>.\Debug\</ProgramDataBaseFileName>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
      <TreatWChar_tAsBuiltInType>false</TreatWChar_tAsBuiltInType>
    </ClCompile>
    <Midl>
      <TypeLibraryName>.\Debug\DBFPassScheduler.tlb</TypeLibraryName>
    </Midl>
    <ResourceCompile>
      <Culture>0x1009</Culture>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
    <Bscmake>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <OutputFile>.\Debug\DBFPassScheduler.bsc</OutputFile>
    </Bscmake>
    <Link>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <SubSystem>Console</SubSystem>
      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>
      <AdditionalDependencies>odbc32.lib;odbccp32.lib;ws2_32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <IgnoreSpecificDefaultLibraries>
      </IgnoreSpecificDefaultLibraries>
      <IgnoreAllDefaultLibraries>false</IgnoreAllDefaultLibraries>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <ClCompile>
      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
      <InlineFunctionExpansion>OnlyExplicitInline</InlineFunctionExpansion>
      <StringPooling>true</StringPooling>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <Optimization>MaxSpeed</Optimization>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <WarningLevel>Level3</WarningLevel>
      <AdditionalIncludeDirectories>..\common\include;..\3rd party\microsoft\microsoft sdk\include;..\3rd party\microsoft\msxml4;..\..\common\include;..\..\3rd party\microsoft\microsoft sdk\include;..\..\3rd party\microsoft\msxml4;..\ADBoards\GS;..ADBoards\GS - 64\Include;..\3rdparty\intel\ipp\5.2\ia32\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>NDEBUG;WIN32;_CONSOLE;_WIN32_WINNT=0x400;EMS_USE_INTEL_PP;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AssemblerListingLocation>.\Release\</AssemblerListingLocation>
      <PrecompiledHeaderOutputFile>.\Release\DBFPassScheduler.pch</PrecompiledHeaderOutputFile>
      <ObjectFileName>.\Release\</ObjectFileName>
      <ProgramDataBaseFileName>.\Release\</ProgramDataBaseFileName>
    </ClCompile>
    <Midl>
      <TypeLibraryName>.\Release\DBFPassScheduler.tlb</TypeLibraryName>
    </Midl>
    <ResourceCompile>
      <Culture>0x1009</Culture>
      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
    <Bscmake>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <OutputFile>.\Release\DBFPassScheduler.bsc</OutputFile>
    </Bscmake>
    <Link>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <SubSystem>Console</SubSystem>
      <OutputFile>Release/EMSDBFPassScheduler.exe</OutputFile>
      <AdditionalDependencies>odbc32.lib;odbccp32.lib;ws2_32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <GenerateDebugInformation>false</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="..\Common\AOBJBASE.CPP" />
    <ClCompile Include="..\Common\ccbootstrap.cpp" />
    <ClCompile Include="..\Common\ConfigurationAccessor.cpp" />
    <ClCompile Include="..\Common\convutility.cpp" />
    <ClCompile Include="..\Common\EMSCONFG.CPP" />
    <ClCompile Include="..\Common\emsoutlier.cpp" />
    <ClCompile Include="..\Common\EMSRGKEY.CPP" />
    <ClCompile Include="..\Common\LOGEVENT.CPP" />
    <ClCompile Include="..\Common\LogHelper.cpp" />
    <ClCompile Include="DBFDataMgr.cpp" />
    <ClCompile Include="DBFNullPointing.cpp" />
    <ClCompile Include="DBFPassScheduler.cpp" />
    <ClCompile Include="DBFPhaseHandling.cpp" />
    <ClCompile Include="DBFPointingAngles.cpp" />
    <ClCompile Include="..\Common\EMSCLOCK.CPP" />
    <ClCompile Include="..\Common\EMSCMREG.CPP" />
    <ClCompile Include="..\Common\EMSCOORD.CPP" />
    <ClCompile Include="..\Common\emsdomdocument.cpp" />
    <ClCompile Include="..\Common\emsdomnode.cpp" />
    <ClCompile Include="..\Common\emsdomnodelist.cpp" />
    <ClCompile Include="..\Common\EMSEARTH.CPP" />
    <ClCompile Include="..\Common\EMSENCOD.CPP" />
    <ClCompile Include="..\Common\EMSEXCPT.CPP" />
    <ClCompile Include="..\Common\EMSRANGE.CPP" />
    <ClCompile Include="..\Common\Emssun.cpp" />
    <ClCompile Include="..\Common\EMSTIME.CPP" />
    <ClCompile Include="..\Common\EMSVECTR.CPP" />
    <ClCompile Include="..\Common\ESECDESC.CPP" />
    <ClCompile Include="..\Common\Eservice.cpp" />
    <ClCompile Include="..\Common\LogMsgParam.cpp" />
    <ClCompile Include="..\Common\LogRegistrySettings.cpp" />
    <ClCompile Include="..\Common\RegistrySettings.cpp" />
    <ClCompile Include="SIGPROC.CPP" />
    <ClCompile Include="StdAfx.cpp">
      <PrecompiledHeader Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">Create</PrecompiledHeader>
      <PrecompiledHeaderFile Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">stdafx.h</PrecompiledHeaderFile>
      <PrecompiledHeader Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">Create</PrecompiledHeader>
      <PrecompiledHeaderFile Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">stdafx.h</PrecompiledHeaderFile>
    </ClCompile>
  </ItemGroup>
  <ItemGroup>
    <ClInclude Include="CSVReader.h" />
    <ClInclude Include="StdAfx.h" />
  </ItemGroup>
  <ItemGroup>
    <Library Include="..\3rdParty\Intel\IPP\5.2\ia32\stublib\ippm.lib" />
    <Library Include="..\3rdParty\Intel\IPP\5.2\ia32\stublib\ipps.lib" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
</Project>