// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema
// to C++ data binding compiler, in the Proprietary License mode.
// You should have received a proprietary license from Code Synthesis
// Tools CC prior to generating this code. See the license text for
// conditions.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "DBFConstellation.hxx"

namespace dbfconstellation
{
  // computer
  // 

  const computer::Switch_type& computer::
  Switch () const
  {
    return this->Switch_.get ();
  }

  computer::Switch_type& computer::
  Switch ()
  {
    return this->Switch_.get ();
  }

  void computer::
  Switch (const Switch_type& x)
  {
    this->Switch_.set (x);
  }

  const computer::SynthesizerIP_type& computer::
  SynthesizerIP () const
  {
    return this->SynthesizerIP_.get ();
  }

  computer::SynthesizerIP_type& computer::
  SynthesizerIP ()
  {
    return this->SynthesizerIP_.get ();
  }

  void computer::
  SynthesizerIP (const SynthesizerIP_type& x)
  {
    this->SynthesizerIP_.set (x);
  }

  void computer::
  SynthesizerIP (::std::auto_ptr< SynthesizerIP_type > x)
  {
    this->SynthesizerIP_.set (x);
  }

  const computer::EnvSensorIP_type& computer::
  EnvSensorIP () const
  {
    return this->EnvSensorIP_.get ();
  }

  computer::EnvSensorIP_type& computer::
  EnvSensorIP ()
  {
    return this->EnvSensorIP_.get ();
  }

  void computer::
  EnvSensorIP (const EnvSensorIP_type& x)
  {
    this->EnvSensorIP_.set (x);
  }

  void computer::
  EnvSensorIP (::std::auto_ptr< EnvSensorIP_type > x)
  {
    this->EnvSensorIP_.set (x);
  }

  const computer::FrequencyOffset_optional& computer::
  FrequencyOffset () const
  {
    return this->FrequencyOffset_;
  }

  computer::FrequencyOffset_optional& computer::
  FrequencyOffset ()
  {
    return this->FrequencyOffset_;
  }

  void computer::
  FrequencyOffset (const FrequencyOffset_type& x)
  {
    this->FrequencyOffset_.set (x);
  }

  void computer::
  FrequencyOffset (const FrequencyOffset_optional& x)
  {
    this->FrequencyOffset_ = x;
  }

  const computer::id_type& computer::
  id () const
  {
    return this->id_.get ();
  }

  computer::id_type& computer::
  id ()
  {
    return this->id_.get ();
  }

  void computer::
  id (const id_type& x)
  {
    this->id_.set (x);
  }

  void computer::
  id (::std::auto_ptr< id_type > x)
  {
    this->id_.set (x);
  }


  // computers
  // 

  const computers::computer_sequence& computers::
  computer () const
  {
    return this->computer_;
  }

  computers::computer_sequence& computers::
  computer ()
  {
    return this->computer_;
  }

  void computers::
  computer (const computer_sequence& s)
  {
    this->computer_ = s;
  }

  const computers::SP_type& computers::
  SP () const
  {
    return this->SP_.get ();
  }

  computers::SP_type& computers::
  SP ()
  {
    return this->SP_.get ();
  }

  void computers::
  SP (const SP_type& x)
  {
    this->SP_.set (x);
  }

  void computers::
  SP (::std::auto_ptr< SP_type > x)
  {
    this->SP_.set (x);
  }

  const computers::version_type& computers::
  version () const
  {
    return this->version_.get ();
  }

  computers::version_type& computers::
  version ()
  {
    return this->version_.get ();
  }

  void computers::
  version (const version_type& x)
  {
    this->version_.set (x);
  }

  void computers::
  version (::std::auto_ptr< version_type > x)
  {
    this->version_.set (x);
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace dbfconstellation
{
  // computer
  //

  computer::
  computer (const Switch_type& Switch,
            const SynthesizerIP_type& SynthesizerIP,
            const EnvSensorIP_type& EnvSensorIP,
            const id_type& id)
  : ::xml_schema::type (),
    Switch_ (Switch, ::xml_schema::flags (), this),
    SynthesizerIP_ (SynthesizerIP, ::xml_schema::flags (), this),
    EnvSensorIP_ (EnvSensorIP, ::xml_schema::flags (), this),
    FrequencyOffset_ (::xml_schema::flags (), this),
    id_ (id, ::xml_schema::flags (), this)
  {
  }

  computer::
  computer (const computer& x,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    Switch_ (x.Switch_, f, this),
    SynthesizerIP_ (x.SynthesizerIP_, f, this),
    EnvSensorIP_ (x.EnvSensorIP_, f, this),
    FrequencyOffset_ (x.FrequencyOffset_, f, this),
    id_ (x.id_, f, this)
  {
  }

  computer::
  computer (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    Switch_ (f, this),
    SynthesizerIP_ (f, this),
    EnvSensorIP_ (f, this),
    FrequencyOffset_ (f, this),
    id_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
      this->parse (p, f);
    }
  }

  void computer::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // Switch
      //
      if (n.name () == "Switch" && n.namespace_ ().empty ())
      {
        if (!Switch_.present ())
        {
          this->Switch_.set (Switch_traits::create (i, f, this));
          continue;
        }
      }

      // SynthesizerIP
      //
      if (n.name () == "SynthesizerIP" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< SynthesizerIP_type > r (
          SynthesizerIP_traits::create (i, f, this));

        if (!SynthesizerIP_.present ())
        {
          this->SynthesizerIP_.set (r);
          continue;
        }
      }

      // EnvSensorIP
      //
      if (n.name () == "EnvSensorIP" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< EnvSensorIP_type > r (
          EnvSensorIP_traits::create (i, f, this));

        if (!EnvSensorIP_.present ())
        {
          this->EnvSensorIP_.set (r);
          continue;
        }
      }

      // FrequencyOffset (optional – primitive float, no auto_ptr)
      //
      if (n.name () == "FrequencyOffset" && n.namespace_ ().empty ())
      {
        if (!FrequencyOffset_.present ())
        {
          this->FrequencyOffset_.set (FrequencyOffset_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }

    if (!Switch_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "Switch",
        "");
    }

    if (!SynthesizerIP_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "SynthesizerIP",
        "");
    }

    if (!EnvSensorIP_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "EnvSensorIP",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "id" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< id_type > r (
          id_traits::create (i, f, this));

        this->id_.set (r);
        continue;
      }
    }

    if (!id_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "id",
        "");
    }
  }

  computer* computer::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class computer (*this, f, c);
  }

  computer::
  ~computer ()
  {
  }

  // computers
  //

  computers::
  computers (const SP_type& SP,
             const version_type& version)
  : ::xml_schema::type (),
    computer_ (::xml_schema::flags (), this),
    SP_ (SP, ::xml_schema::flags (), this),
    version_ (version, ::xml_schema::flags (), this)
  {
  }

  computers::
  computers (const computers& x,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    computer_ (x.computer_, f, this),
    SP_ (x.SP_, f, this),
    version_ (x.version_, f, this)
  {
  }

  computers::
  computers (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    computer_ (f, this),
    SP_ (f, this),
    version_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
      this->parse (p, f);
    }
  }

  void computers::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // computer
      //
      if (n.name () == "computer" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< computer_type > r (
          computer_traits::create (i, f, this));

        this->computer_.push_back (r);
        continue;
      }

      // SP
      //
      if (n.name () == "SP" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< SP_type > r (
          SP_traits::create (i, f, this));

        if (!SP_.present ())
        {
          this->SP_.set (r);
          continue;
        }
      }

      break;
    }

    if (!SP_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "SP",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "version" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< version_type > r (
          version_traits::create (i, f, this));

        this->version_.set (r);
        continue;
      }
    }

    if (!version_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "version",
        "");
    }
  }

  computers* computers::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class computers (*this, f, c);
  }

  computers::
  ~computers ()
  {
  }
}

#include <ostream>

namespace dbfconstellation
{
  ::std::ostream&
  operator<< (::std::ostream& o, const computer& i)
  {
    o << ::std::endl << "Switch: " << i.Switch ();
    o << ::std::endl << "SynthesizerIP: " << i.SynthesizerIP ();
    o << ::std::endl << "EnvSensorIP: " << i.EnvSensorIP ();
    if (i.FrequencyOffset ().present ())
      o << ::std::endl << "FrequencyOffset: " << i.FrequencyOffset ().get ();
    o << ::std::endl << "id: " << i.id ();
    return o;
  }

  ::std::ostream&
  operator<< (::std::ostream& o, const computers& i)
  {
    for (computers::computer_const_iterator
         b (i.computer ().begin ()), e (i.computer ().end ());
         b != e; ++b)
    {
      o << ::std::endl << "computer: " << *b;
    }

    o << ::std::endl << "SP: " << i.SP ();
    o << ::std::endl << "version: " << i.version ();
    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace dbfconstellation
{
  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (const ::std::string& u,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::dbfconstellation::computers > r (
      ::dbfconstellation::computers_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (const ::std::string& u,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::dbfconstellation::computers > r (
      ::dbfconstellation::computers_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (const ::std::string& u,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::dbfconstellation::computers > r (
      ::dbfconstellation::computers_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::std::istream& is,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::dbfconstellation::computers_ (isrc, f, p);
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::std::istream& is,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::dbfconstellation::computers_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::std::istream& is,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::dbfconstellation::computers_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::std::istream& is,
              const ::std::string& sid,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::dbfconstellation::computers_ (isrc, f, p);
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::std::istream& is,
              const ::std::string& sid,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::dbfconstellation::computers_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::std::istream& is,
              const ::std::string& sid,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::dbfconstellation::computers_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::xercesc::InputSource& i,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::dbfconstellation::computers > r (
      ::dbfconstellation::computers_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::xercesc::InputSource& i,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::dbfconstellation::computers > r (
      ::dbfconstellation::computers_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::xercesc::InputSource& i,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::dbfconstellation::computers > r (
      ::dbfconstellation::computers_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (const ::xercesc::DOMDocument& d,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
        static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

      ::std::auto_ptr< ::dbfconstellation::computers > r (
        ::dbfconstellation::computers_ (
          c, f | ::xml_schema::flags::own_dom, p));

      return r;
    }

    const ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "computers" &&
        n.namespace_ () == "urn:dbfconstellation")
    {
      ::std::auto_ptr< ::dbfconstellation::computers > r (
        ::xsd::cxx::tree::traits< ::dbfconstellation::computers, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "computers",
      "urn:dbfconstellation");
  }

  ::std::auto_ptr< ::dbfconstellation::computers >
  computers_ (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
              ::xml_schema::flags f,
              const ::xml_schema::properties&)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (f & ::xml_schema::flags::keep_dom)
      doc.setUserData (::xml_schema::dom::tree_node_key,
                       (c.get () ? &c : &d),
                       0);

    if (n.name () == "computers" &&
        n.namespace_ () == "urn:dbfconstellation")
    {
      ::std::auto_ptr< ::dbfconstellation::computers > r (
        ::xsd::cxx::tree::traits< ::dbfconstellation::computers, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "computers",
      "urn:dbfconstellation");
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace dbfconstellation
{
  void
  computers_ (::std::ostream& o,
              const ::dbfconstellation::computers& s,
              const ::xml_schema::namespace_infomap& m,
              const ::std::string& e,
              ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::dbfconstellation::computers_ (s, m, f));

    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
    }
  }

  void
  computers_ (::std::ostream& o,
              const ::dbfconstellation::computers& s,
              ::xml_schema::error_handler& h,
              const ::xml_schema::namespace_infomap& m,
              const ::std::string& e,
              ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::dbfconstellation::computers_ (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  computers_ (::std::ostream& o,
              const ::dbfconstellation::computers& s,
              ::xercesc::DOMErrorHandler& h,
              const ::xml_schema::namespace_infomap& m,
              const ::std::string& e,
              ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::dbfconstellation::computers_ (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  computers_ (::xercesc::XMLFormatTarget& t,
              const ::dbfconstellation::computers& s,
              const ::xml_schema::namespace_infomap& m,
              const ::std::string& e,
              ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::dbfconstellation::computers_ (s, m, f));

    ::xsd::cxx::tree::error_handler< char > h;

    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
    }
  }

  void
  computers_ (::xercesc::XMLFormatTarget& t,
              const ::dbfconstellation::computers& s,
              ::xml_schema::error_handler& h,
              const ::xml_schema::namespace_infomap& m,
              const ::std::string& e,
              ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::dbfconstellation::computers_ (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  computers_ (::xercesc::XMLFormatTarget& t,
              const ::dbfconstellation::computers& s,
              ::xercesc::DOMErrorHandler& h,
              const ::xml_schema::namespace_infomap& m,
              const ::std::string& e,
              ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::dbfconstellation::computers_ (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  computers_ (::xercesc::DOMDocument& d,
              const ::dbfconstellation::computers& s,
              ::xml_schema::flags)
  {
    ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "computers" &&
        n.namespace_ () == "urn:dbfconstellation")
    {
      e << s;
    }
    else
    {
      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "computers",
        "urn:dbfconstellation");
    }
  }

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
  computers_ (const ::dbfconstellation::computers& s,
              const ::xml_schema::namespace_infomap& m,
              ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::serialize< char > (
        "computers",
        "urn:dbfconstellation",
        m, f));

    ::dbfconstellation::computers_ (*d, s, f);
    return d;
  }

  void
  operator<< (::xercesc::DOMElement& e, const computer& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // Switch
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "Switch",
          e));

      s << i.Switch ();
    }

    // SynthesizerIP
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "SynthesizerIP",
          e));

      s << i.SynthesizerIP ();
    }

    // EnvSensorIP
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "EnvSensorIP",
          e));

      s << i.EnvSensorIP ();
    }

    // FrequencyOffset (optional)
    //
    if (i.FrequencyOffset ().present ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "FrequencyOffset",
          e));

      s << i.FrequencyOffset ().get ();
    }

    // id
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "id",
          e));

      a << i.id ();
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const computers& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // computer
    //
    for (computers::computer_const_iterator
         b (i.computer ().begin ()), n (i.computer ().end ());
         b != n; ++b)
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "computer",
          e));

      s << *b;
    }

    // SP
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "SP",
          e));

      s << i.SP ();
    }

    // version
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "version",
          e));

      a << i.version ();
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

